### PR TITLE
fix: node 14+ changes how multiple destroy() calls work

### LINKED ISSUE #1154: Some old cruft plus Node 14 changes broke stream tests
This is mostly a tracking issue for the fix below. It's currently stopping us from merging any other PRs.

Fixed by: https://github.com/googleapis/nodejs-pubsub/pull/1153

### PR DESCRIPTION
**Pull request by feywind**
Also, this relied on node <14 behaviour, so there were weird conflicts with the standard stream library. There was also some cruft from Node <8 support that needs to go away with the implementation being normalized.

### CODE REVIEW

**Comment by alexander-fenster** [comment]
@feywind I hacked a little bit in your branch to make the CI pass here. It indeed fixes the tests, thank you!

File: src/message-stream.ts [hunk 1]
```diff
@@ -156,14 +154,27 @@ export class MessageStream extends PassThrough {
   /**
    * Destroys the stream and any underlying streams.
    *
-   * @param {error?} err An error to emit, if any.
+   * @param {error?} _error An error to emit, if any.
    * @private
    */
-  destroy(err?: Error): void {
+  destroy(_error?: Error | null): void {
```
Comment (alexander-fenster) [inline src/message-stream.ts:160]: style nit here and below, why underscores?

**Review by alexander-fenster — APPROVED** [review]

File: src/message-stream.ts (hunk 1 above)
Comment (feywind) [reply src/message-stream.ts:160]: Oh, this was more or less copied out of the definitions from the Node stream library. I don't think there's a particular reason for it, so I'll move them back to no underscores.
