### PR TITLE
refactor: type fixes and some light housekeeping

### LINKED ISSUE #507: Invalid typings
#### Environment details

  - OS: irrelevant
  - Node.js version: irrelevant
  - npm version: irrelevant
  - `@google-cloud/pubsub` version: 0.26.0

It looks like the typings shipped with 0.26.0 are incorrect. I can't see any difference in actual implementation nor the changelog that would explain these changes:
- `Topic.exists` has a required parameter - a callback. It should return void if provided with a callback, a promise otherwise.
- `Topic.get` returns a `Topic`, not `[Topic]` as it used to. Although I'd gladly welcome this change to the interface, it seems that it actually didn't change and still returns an array.

There might be more, I just pointed out the ones I've came across and tested.

### LINKED ISSUE #526: I just tried to upgrade and I am getting many cannot find type "Long" error
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: Mac OS X
  - Node.js version: node v10
  - npm version: yarn 1.13.0
  - `@google-cloud/pubsub` version: Current 0.24.1  Tried to Upgrade to 0.27.0

#### Steps to reproduce

  1. Setup existing project using typescript
  2. Upgrade from 0.24.1 to 0.27.0

I don't know if there are other causes or setups I need to do. I have tried to add "types: ['Long']" into the compiler configuration but that didn't help. I found references to some other projects also using protobuf with similar problems, but I was unable to find a place where it presented a good solution.
I tried quite a few different approaches, but didn't get anywhere, sorry.

### PR DESCRIPTION
**Pull request by callmehiphop**
Fixes #507
Fixes #526
Closes #525

- [x] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

File: test/snapshot.ts [hunk 1]
```diff
@@ -233,14 +233,5 @@ describe('Snapshot', () => {
 
       snapshot.delete(done);
     });
-
```
Comment (JustinBeckwith) [inline test/snapshot.ts]: So...  what's up with the deleted test?

Comment (callmehiphop) [reply test/snapshot.ts]: They were useless. We would do a `callback = callback || noop` but callback will never be undefined because omitting it just users the promisified version.

**Comment by JustinBeckwith** [comment]
LGTM, assuming tests pass :)
