### PR TITLE
fix: propagate set options to LeaseManager (from https://github.com/googleapis/nodejs-pubsub/pull/1880)

### LINKED ISSUE #1879: calling setOptions on subscriber does not take effect
if changing flowControl settings after calling .on they dont not get into effect

```
const subscription = pubSubClient.subscription(subscriptionNameOrId);
const messageHandler = message => {

  message.ack();
};

subscription.on('message', messageHandler);

// does not have any effect on flow control
subscription.setOptions({
flowControl: {
          maxMessages: 1,
          allowExcessMessages: true,
 }
})

```

### PR DESCRIPTION
**Pull request by feywind**
Bringing this over from https://github.com/googleapis/nodejs-pubsub/pull/1880 (dermasmid@) so I can work CI on it.

Fixes https://github.com/googleapis/nodejs-pubsub/issues/1879

### CODE REVIEW

**Review by hongalex — APPROVED** [review]

File: src/subscriber.ts [hunk 1]
```diff
@@ -771,11 +771,22 @@ export class Subscriber extends EventEmitter {
...
       const {maxStreams = defaultOptions.subscription.maxStreams} =
         options.streamingOptions;
+
       options.streamingOptions.maxStreams = Math.min(
         maxStreams,
         this.maxMessages
       );
     }
+
+    if (this._acks) {
```
Comment (hongalex) [inline src/subscriber.ts:781]: Let's not expose these settings more than they already are, since we don't want users to be able to set these batching settings. Flow control is ok though
